/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;
import modelos.Conjunto;
import javax.swing.JOptionPane;
/**
 *
 * @author alexandermartins
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    //Atributos
    
    Conjunto ca = null;
    Conjunto cb = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextFieldIncluirCA.setEnabled(false);
        jTextFieldIncluirCB.setEnabled(false);
        jButtonIncluirCA.setEnabled(false);
        jButtonIncluirCB.setEnabled(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTamanhoCA = new javax.swing.JTextField();
        jTextFieldIncluirCA = new javax.swing.JTextField();
        jButtonCriarCA = new javax.swing.JButton();
        jButtonIncluirCA = new javax.swing.JButton();
        jTextFieldSaidaCA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTamanhoCB = new javax.swing.JTextField();
        jTextFieldIncluirCB = new javax.swing.JTextField();
        jButtonCriarCB = new javax.swing.JButton();
        jButtonIncluirCB = new javax.swing.JButton();
        jTextFieldSaidaCB = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonInterseccao = new javax.swing.JButton();
        jButtonCADifCB = new javax.swing.JButton();
        jButtonCBDifCA = new javax.swing.JButton();
        jButtonUniao = new javax.swing.JButton();
        jTextFieldResultado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONJUNTO A");

        jLabel2.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TAMANHO");

        jLabel3.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INCLUIR");

        jTextFieldTamanhoCA.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldTamanhoCA.setFont(new java.awt.Font("Adwaita Sans", 1, 16)); // NOI18N
        jTextFieldTamanhoCA.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldIncluirCA.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldIncluirCA.setFont(new java.awt.Font("Adwaita Sans", 1, 16)); // NOI18N
        jTextFieldIncluirCA.setForeground(new java.awt.Color(255, 255, 255));

        jButtonCriarCA.setBackground(new java.awt.Color(102, 102, 102));
        jButtonCriarCA.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCriarCA.setText("CRIAR");
        jButtonCriarCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarCAActionPerformed(evt);
            }
        });

        jButtonIncluirCA.setBackground(new java.awt.Color(102, 102, 102));
        jButtonIncluirCA.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIncluirCA.setText("INCLUIR");
        jButtonIncluirCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirCAActionPerformed(evt);
            }
        });

        jTextFieldSaidaCA.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldSaidaCA.setFont(new java.awt.Font("Adwaita Sans", 1, 16)); // NOI18N
        jTextFieldSaidaCA.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONJUNTO B");

        jLabel5.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TAMANHO");

        jLabel6.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("INCLUIR");

        jTextFieldTamanhoCB.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldTamanhoCB.setFont(new java.awt.Font("Adwaita Sans", 1, 16)); // NOI18N
        jTextFieldTamanhoCB.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldIncluirCB.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldIncluirCB.setFont(new java.awt.Font("Adwaita Sans", 1, 16)); // NOI18N
        jTextFieldIncluirCB.setForeground(new java.awt.Color(255, 255, 255));

        jButtonCriarCB.setBackground(new java.awt.Color(102, 102, 102));
        jButtonCriarCB.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCriarCB.setText("CRIAR");
        jButtonCriarCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarCBActionPerformed(evt);
            }
        });

        jButtonIncluirCB.setBackground(new java.awt.Color(102, 102, 102));
        jButtonIncluirCB.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIncluirCB.setText("INCLUIR");
        jButtonIncluirCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirCBActionPerformed(evt);
            }
        });

        jTextFieldSaidaCB.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldSaidaCB.setFont(new java.awt.Font("Adwaita Sans", 1, 16)); // NOI18N
        jTextFieldSaidaCB.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        jButtonInterseccao.setBackground(new java.awt.Color(102, 102, 102));
        jButtonInterseccao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInterseccao.setText("CA ∩ CB");
        jButtonInterseccao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInterseccaoActionPerformed(evt);
            }
        });

        jButtonCADifCB.setBackground(new java.awt.Color(102, 102, 102));
        jButtonCADifCB.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCADifCB.setText("CA - CB");
        jButtonCADifCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCADifCBActionPerformed(evt);
            }
        });

        jButtonCBDifCA.setBackground(new java.awt.Color(102, 102, 102));
        jButtonCBDifCA.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCBDifCA.setText("CB - CA");
        jButtonCBDifCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCBDifCAActionPerformed(evt);
            }
        });

        jButtonUniao.setBackground(new java.awt.Color(102, 102, 102));
        jButtonUniao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUniao.setText("CA ∪ CB");
        jButtonUniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUniaoActionPerformed(evt);
            }
        });

        jTextFieldResultado.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldResultado.setFont(new java.awt.Font("Adwaita Sans", 1, 16)); // NOI18N
        jTextFieldResultado.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Adwaita Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Resultado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButtonUniao)
                .addGap(111, 111, 111)
                .addComponent(jButtonInterseccao)
                .addGap(121, 121, 121)
                .addComponent(jButtonCADifCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCBDifCA)
                .addGap(116, 116, 116))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInterseccao)
                    .addComponent(jButtonCADifCB)
                    .addComponent(jButtonCBDifCA)
                    .addComponent(jButtonUniao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldTamanhoCA)
                                    .addComponent(jTextFieldIncluirCA, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCriarCA, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonIncluirCA)))
                            .addComponent(jTextFieldSaidaCA))))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTamanhoCB)
                            .addComponent(jTextFieldIncluirCB, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCriarCB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonIncluirCB)))
                    .addComponent(jTextFieldSaidaCB, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(63, 63, 63))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldTamanhoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCriarCB))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldIncluirCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonIncluirCB))
                        .addGap(39, 39, 39)
                        .addComponent(jTextFieldSaidaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldTamanhoCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCriarCA))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldIncluirCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonIncluirCA))
                        .addGap(39, 39, 39)
                        .addComponent(jTextFieldSaidaCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCriarCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarCAActionPerformed
        // TODO add your handling code here:
        
        try {
            int tamanho = Integer.parseInt(jTextFieldTamanhoCA.getText());
            ca = new Conjunto(tamanho);
            
        jTextFieldIncluirCA.setEnabled(true);
        jButtonIncluirCA.setEnabled(true);
        jTextFieldTamanhoCA.setEnabled(false);
        jButtonCriarCA.setEnabled(false);
      
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonCriarCAActionPerformed

    private void jButtonIncluirCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirCAActionPerformed
        // TODO add your handling code here:
        
        try {
            int elemento = Integer.parseInt(jTextFieldIncluirCA.getText());
            ca.incluir(elemento);
            
            jTextFieldSaidaCA.setText(ca.obterDadosDoArray());
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirCAActionPerformed

    private void jButtonCriarCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarCBActionPerformed
        // TODO add your handling code here:
        
        try {
            int tamanho = Integer.parseInt(jTextFieldTamanhoCB.getText());
            cb = new Conjunto(tamanho);
            
        jTextFieldIncluirCB.setEnabled(true);
        jButtonIncluirCB.setEnabled(true);
        jButtonCriarCB.setEnabled(false); 
        jTextFieldTamanhoCB.setEnabled(false);
        
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonCriarCBActionPerformed

    private void jButtonIncluirCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirCBActionPerformed
        // TODO add your handling code here:
        
        try {
            int elemento = Integer.parseInt(jTextFieldIncluirCB.getText());
            cb.incluir(elemento);
            
            jTextFieldSaidaCB.setText(cb.obterDadosDoArray());
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirCBActionPerformed

    private void jButtonInterseccaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInterseccaoActionPerformed
        // TODO add your handling code here:
        
        try {
            
            jTextFieldResultado.setText(cb.gerarInterseccao(ca).obterDadosDoArray());
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonInterseccaoActionPerformed

    private void jButtonCADifCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCADifCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCADifCBActionPerformed

    private void jButtonCBDifCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCBDifCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCBDifCAActionPerformed

    private void jButtonUniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUniaoActionPerformed
        // TODO add your handling code here:
        
        try {
            
            jTextFieldResultado.setText(ca.gerarUniao(cb).obterDadosDoArray());
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonUniaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCADifCB;
    private javax.swing.JButton jButtonCBDifCA;
    private javax.swing.JButton jButtonCriarCA;
    private javax.swing.JButton jButtonCriarCB;
    private javax.swing.JButton jButtonIncluirCA;
    private javax.swing.JButton jButtonIncluirCB;
    private javax.swing.JButton jButtonInterseccao;
    private javax.swing.JButton jButtonUniao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldIncluirCA;
    private javax.swing.JTextField jTextFieldIncluirCB;
    private javax.swing.JTextField jTextFieldResultado;
    private javax.swing.JTextField jTextFieldSaidaCA;
    private javax.swing.JTextField jTextFieldSaidaCB;
    private javax.swing.JTextField jTextFieldTamanhoCA;
    private javax.swing.JTextField jTextFieldTamanhoCB;
    // End of variables declaration//GEN-END:variables
}
